/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.ArmasD;
import static VistasInterfazD.CrearArmas.contenedor2;
import static VistasInterfazD.CrearArmas.jTextFieldNombreArma;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static proyectofinaldaniel.ProyectoFinalDaniel.pathArmasD;

/**
 *
 * @author danie
 */
public class AEstadisticas extends javax.swing.JFrame {
private DefaultTableModel modelo;
    int cont = 0;//contador armas
    /**
     * Constructor de las estadísticas de las armas
     * Creates new form AEstadisticas
     */
    public AEstadisticas() {
        initComponents();
        setSize(1490, 1200);
        setTitle("FEROVA GAME");
        CargarRegistrarA();
         readBinarioD();
        CargardatosA();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegresarE = new javax.swing.JButton();
        jButtonSalirE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadisticasA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegresarE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarE.setForeground(new java.awt.Color(0, 255, 51));
        jButtonRegresarE.setText("Regresar");
        jButtonRegresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 840, 240, 100));

        jButtonSalirE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonSalirE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirE.setText("Salir del Juego");
        jButtonSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirE, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 860, 270, 110));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Condensed", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("ARMAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 210, 70));

        jTableEstadisticasA.setBackground(new java.awt.Color(255, 255, 255));
        jTableEstadisticasA.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTableEstadisticasA.setForeground(new java.awt.Color(0, 0, 0));
        jTableEstadisticasA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Punteria", "Ataque", "Ataque"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadisticasA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 980, 540));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Método para registrar mis datos de Tienda
 */
    public void CargarRegistrarA(){
    String datos [][]= {};
    String columna[]= {"Nombre", "Punteria", "Ataque", "CostoA"};
    //String columna1[] = { "V1" };
    
    modelo= new DefaultTableModel(datos, columna);
    jTableEstadisticasA.setModel(modelo);
    
}
    /**
     * Método para leerlo de forma binaria
     */
     public void readBinarioD(){
        contenedor2.clear();
        ObjectInputStream binario = null;
        try {
            String nameFile = jTextFieldNombreArma.getText();
            File filearma = new File("ArmasD");
            
            
            
            for (String string2:filearma.list()) {
                
                binario = new ObjectInputStream(new FileInputStream(pathArmasD+string2));
                ArmasD ar = (ArmasD) binario.readObject();
                contenedor2.add(ar);
                
            }
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException e) {
                Logger.getLogger(CrearArmas.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        
    } 
     /**
      * Método para cargar los datos de las armas
      */
     public void CargardatosA(){
                ArmasD a;
                //Registrar b;
                for (int i = 0; i < CrearArmas.contenedor2.size(); i++) {
                    a= (ArmasD)CrearArmas.contenedor2.get(i);
                  //  b= (Registrar) Registrar.contenedor.get(i);
                    modelo.insertRow(cont, new Object []{ });
                    modelo.setValueAt(a.getNombreA(), cont, 0);
                    modelo.setValueAt(a.getPunteriaA(), cont, 1);
                    modelo.setValueAt(a.getAtaqueA(), cont, 2);
                    modelo.setValueAt(a.getCostoA(), cont, 3);
                 
                     
                    
                    
                    
                }
                    
                
                
            }
    /**
     * Método para salir del juego
     * @param evt 
     */
    private void jButtonSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEActionPerformed
/**
 * Método para regresaar a Tienda 
 * @param evt 
 */
    private void jButtonRegresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarEActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

        new Tienda().setVisible(true);
        setSize(825, 866);
        dispose();
    }//GEN-LAST:event_jButtonRegresarEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegresarE;
    private javax.swing.JButton jButtonSalirE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadisticasA;
    // End of variables declaration//GEN-END:variables

    String getArma() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
