/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.ArmasD;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.LinkedList;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.logging.Logger;
import static proyectofinaldaniel.ProyectoFinalDaniel.pathArmasD;
import static VistasInterfazD.CrearArmas.contenedor2;
import static VistasInterfazD.CrearArmas.jTextFieldNombreArma;

/**
 *
 * @author danie
 */
public class CrearArmas extends javax.swing.JFrame {
 public static LinkedList contenedor2 = new LinkedList();
    public int buscar;
    /**
     * Constructor de mi JFRAME CrearArmas
     * Creates new form CrearArmas
     */
    public CrearArmas() {
        initComponents();
           this.setLocationRelativeTo(null);
           setSize(1290, 1000);
           setTitle("FEROVA GAME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonArmas1 = new javax.swing.JButton();
        jButtonRegresarTipos = new javax.swing.JButton();
        jButtonGuardarArma = new javax.swing.JButton();
        jTextFieldNombreArma = new javax.swing.JTextField();
        jTextFielAtaqueA = new javax.swing.JTextField();
        jTextFielPunteriaA = new javax.swing.JTextField();
        jTextFieldCostoA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COSTO DEL ARMA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 420, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Creación de Armas");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 450, 100));

        jButtonArmas1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonArmas1.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonArmas1.setForeground(new java.awt.Color(0, 255, 0));
        jButtonArmas1.setText("Ver Armas Creadas");
        jButtonArmas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArmas1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonArmas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 340, 100));

        jButtonRegresarTipos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarTipos.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarTipos.setForeground(new java.awt.Color(0, 255, 0));
        jButtonRegresarTipos.setText("Regresar");
        jButtonRegresarTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarTiposActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 260, 100));

        jButtonGuardarArma.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarArma.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonGuardarArma.setForeground(new java.awt.Color(0, 255, 0));
        jButtonGuardarArma.setText("Guardar arma ");
        jButtonGuardarArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarArmaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardarArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 410, 130));

        jTextFieldNombreArma.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombreArma.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldNombreArma.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombreArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreArmaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 310, -1));

        jTextFielAtaqueA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFielAtaqueA.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFielAtaqueA.setForeground(new java.awt.Color(0, 0, 0));
        jTextFielAtaqueA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielAtaqueAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielAtaqueA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 310, -1));

        jTextFielPunteriaA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFielPunteriaA.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFielPunteriaA.setForeground(new java.awt.Color(0, 0, 0));
        jTextFielPunteriaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielPunteriaAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielPunteriaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 310, -1));

        jTextFieldCostoA.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCostoA.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldCostoA.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCostoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCostoAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCostoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 310, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ingrese puntería:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 420, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese ataque:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 420, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese nombre del arma:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 420, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/arma.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 560, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Método para el binario
     */
      public void createBin(){
        ObjectOutputStream binario = null;
        try {
            String nameFile = jTextFieldNombreArma.getText();
            File file = new File(nameFile);
            ArmasD gun = (ArmasD) contenedor2.getLast();
           
            binario = new ObjectOutputStream(new FileOutputStream(pathArmasD+gun.getNombreA()+".ar"));
            binario.writeObject(gun);
            
        } catch (Exception ex) {
            ex.printStackTrace();
           // Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                binario.close();
            } catch (IOException ex) {
                Logger.getLogger(CrearArmas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    private void jTextFieldNombreArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreArmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreArmaActionPerformed

    private void jTextFielAtaqueAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielAtaqueAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielAtaqueAActionPerformed

    private void jTextFielPunteriaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielPunteriaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielPunteriaAActionPerformed

    private void jTextFieldCostoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCostoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCostoAActionPerformed
/**
 * Método para guardar arma creada
 * @param evt 
 */
    private void jButtonGuardarArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarArmaActionPerformed
        // TODO add your handling code here:
    
        String nombreA = jTextFieldNombreArma.getText();
        String punteriaA = jTextFielPunteriaA.getText();
        String ataqueA = jTextFielAtaqueA.getText();
        String costoA = jTextFieldCostoA.getText();
  
        ArmasD  w = new ArmasD (nombreA, punteriaA, ataqueA, costoA);
        contenedor2.add(w);
        //Limpia
       
        jTextFieldNombreArma.setText("");
        jTextFielPunteriaA.setText("");
        jTextFielAtaqueA.setText("");
           jTextFieldCostoA.setText("");
           
           
             ArmasD arma = (ArmasD)contenedor2.getLast();
        createBin();
    }//GEN-LAST:event_jButtonGuardarArmaActionPerformed
/**
 * Botón para regresar a mi JFRAME Tienda
 * @param evt 
 */
    private void jButtonRegresarTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarTiposActionPerformed
        // TODO add your handling code here:
        //Persona persona = new Persona(jTextFieldNombre.getText() );
        //lista.add(persona);
        this.setVisible(false);

        new Tienda().setVisible(true);

         setSize(825, 866);
          dispose();
        
    }//GEN-LAST:event_jButtonRegresarTiposActionPerformed
/**
 * Método para ir a donde estan guardas las armas
 * @param evt 
 */
    private void jButtonArmas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArmas1ActionPerformed

        CrearArmas d = new CrearArmas();
        d.show();
        d.setVisible(false);

        this.setVisible(false);
        new AEstadisticas().setVisible(true);// TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonArmas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearArmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearArmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArmas1;
    private javax.swing.JButton jButtonGuardarArma;
    private javax.swing.JButton jButtonRegresarTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField jTextFielAtaqueA;
    public static javax.swing.JTextField jTextFielPunteriaA;
    public static javax.swing.JTextField jTextFieldCostoA;
    public static javax.swing.JTextField jTextFieldNombreArma;
    // End of variables declaration//GEN-END:variables
}
