/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasInterfazD;

import ClasesdelProyecto.EstadisticasV;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class VEstadisticas extends javax.swing.JFrame {
private DefaultTableModel modelo;
    int cont = 0;
    /**
     * Creates new form VEstadisticas
     */
    public VEstadisticas() {
        initComponents();
        setSize(1490, 1200);
        setTitle("FEROVA GAME");
        CargarRegistrar();
        Cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalirE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstadisticasV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSalirE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalirE.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonSalirE.setForeground(new java.awt.Color(0, 255, 0));
        jButtonSalirE.setText("Salir del Juego");
        jButtonSalirE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalirE);
        jButtonSalirE.setBounds(870, 780, 270, 110);

        jTableEstadisticasV.setBackground(new java.awt.Color(255, 255, 255));
        jTableEstadisticasV.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jTableEstadisticasV.setForeground(new java.awt.Color(0, 0, 0));
        jTableEstadisticasV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nombre", "Puntería", "Ataque", "Defensa", "Velocidad", "CostoV"
            }
        ));
        jScrollPane1.setViewportView(jTableEstadisticasV);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 100, 980, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesD/FinesseGrande.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1810, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void CargarRegistrar(){
    String datos [][]= {};
    String columna[]= {"Nombre", "Nombre Vehículo1", "Tipo", "Nombre Vehículo2","Tipo","Nombre Vehículo3", "Tipo"};
    String columna1[] = { "V1" };
    
    
        
  
    
    modelo= new DefaultTableModel(datos, columna);
    jTableEstadisticasV.setModel(modelo);
    
}

 public void Cargardatos(){
                EstadisticasV a;
                //Registrar b;
                for (int i = 0; i < CrearV.contenedor1.size(); i++) {
                    a= (EstadisticasV)CrearV.contenedor1.get(i);
                  //  b= (Registrar) Registrar.contenedor.get(i);
                    modelo.insertRow(cont, new Object []{ });
                    modelo.setValueAt(a.getTipoV(), cont, 0);
                    modelo.setValueAt(a.getNombreV(), cont, 1);
                    modelo.setValueAt(a.getPunteriaV(), cont, 2);
                    modelo.setValueAt(a.getAtaqueV(), cont, 3);
                     modelo.setValueAt(a.getDefensaV(), cont, 4);
                     modelo.setValueAt(a.getVelocidadV(), cont, 5);
                             modelo.setValueAt(a.getCostoV(), cont, 6);
                     
                    
                    
                    
                }
                    
                
                
            }
    private void jButtonSalirEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalirE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstadisticasV;
    // End of variables declaration//GEN-END:variables
}
